import { motion } from "framer-motion";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Card, CardContent } from "@/components/ui/card";
import { 
  Recycle, 
  Factory, 
  Home, 
  TrendingDown, 
  DollarSign,
  Leaf,
  Package,
  Trash2,
  Apple
} from "lucide-react";

const wasteTypes = [
  {
    icon: Package,
    title: "Paper & Cardboard",
    description: "Office paper, shipping boxes, packaging materials, newspapers, and magazines.",
    percentage: "35%",
  },
  {
    icon: Recycle,
    title: "Plastics",
    description: "Containers, bottles, packaging films, bags, and various plastic products.",
    percentage: "15%",
  },
  {
    icon: Trash2,
    title: "Metals",
    description: "Aluminum cans, steel containers, scrap metal from operations.",
    percentage: "8%",
  },
  {
    icon: Apple,
    title: "Organics",
    description: "Food waste, yard waste, compostable materials from food service.",
    percentage: "25%",
  },
];

const impacts = [
  {
    icon: DollarSign,
    title: "Cost Impact",
    description: "Poor waste management increases disposal costs by 20-40% for most SMEs. Proper separation can significantly reduce these expenses.",
  },
  {
    icon: Leaf,
    title: "Environmental Impact",
    description: "Contaminated recycling ends up in landfills, contributing to greenhouse gas emissions and resource depletion.",
  },
  {
    icon: TrendingDown,
    title: "Efficiency Impact",
    description: "Disorganized waste handling disrupts operations, reduces productivity, and creates health and safety risks.",
  },
];

const WasteOverview = () => {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-24 lg:pt-32">
        {/* Hero */}
        <section className="py-16 lg:py-24 nature-gradient">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="max-w-3xl"
            >
              <span className="inline-block px-4 py-1.5 rounded-full bg-leaf/10 text-leaf text-sm font-medium mb-4">
                Learn
              </span>
              <h1 className="text-4xl lg:text-6xl font-display font-bold text-foreground mb-6">
                Ontario Waste & Recycling Overview
              </h1>
              <p className="text-lg lg:text-xl text-muted-foreground leading-relaxed">
                Understanding what waste is generated in Ontario, why it matters, and how SMEs can make a positive impact through proper waste management.
              </p>
            </motion.div>
          </div>
        </section>

        {/* IC&I vs Residential */}
        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="max-w-3xl mb-16"
            >
              <h2 className="text-3xl lg:text-4xl font-display font-bold text-foreground mb-6">
                Where Does Waste Come From?
              </h2>
              <p className="text-muted-foreground text-lg leading-relaxed">
                Ontario generates over 12 million tonnes of waste annually. This waste comes from two main sources, each with unique characteristics and management needs.
              </p>
            </motion.div>

            <div className="grid lg:grid-cols-2 gap-8">
              <motion.div
                initial={{ opacity: 0, x: -20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
              >
                <Card variant="feature" className="h-full">
                  <CardContent className="p-8">
                    <div className="w-14 h-14 rounded-2xl bg-forest/10 flex items-center justify-center mb-6">
                      <Factory className="h-7 w-7 text-forest" />
                    </div>
                    <h3 className="text-2xl font-display font-semibold text-foreground mb-4">
                      IC&I Waste (Industrial, Commercial & Institutional)
                    </h3>
                    <p className="text-muted-foreground mb-6 leading-relaxed">
                      Waste generated by businesses, factories, offices, schools, hospitals, and other non-residential sources. This accounts for approximately 60% of Ontario's total waste stream.
                    </p>
                    <ul className="space-y-3">
                      {["Manufacturing facilities", "Retail stores & restaurants", "Office buildings", "Schools & hospitals", "Construction sites"].map((item) => (
                        <li key={item} className="flex items-center gap-2 text-foreground">
                          <div className="w-1.5 h-1.5 rounded-full bg-forest" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, x: 20 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: 0.1 }}
              >
                <Card variant="feature" className="h-full">
                  <CardContent className="p-8">
                    <div className="w-14 h-14 rounded-2xl bg-sky/10 flex items-center justify-center mb-6">
                      <Home className="h-7 w-7 text-sky" />
                    </div>
                    <h3 className="text-2xl font-display font-semibold text-foreground mb-4">
                      Residential Waste
                    </h3>
                    <p className="text-muted-foreground mb-6 leading-relaxed">
                      Waste from households, apartments, and residential properties. While municipalities have historically focused here, IC&I waste represents a larger opportunity for improvement.
                    </p>
                    <ul className="space-y-3">
                      {["Single-family homes", "Apartment buildings", "Condominiums", "Townhouses", "Retirement homes"].map((item) => (
                        <li key={item} className="flex items-center gap-2 text-foreground">
                          <div className="w-1.5 h-1.5 rounded-full bg-sky" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              </motion.div>
            </div>
          </div>
        </section>

        {/* Common Materials */}
        <section className="py-16 lg:py-24 bg-secondary/30">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="text-center max-w-3xl mx-auto mb-16"
            >
              <h2 className="text-3xl lg:text-4xl font-display font-bold text-foreground mb-6">
                Common Materials Generated by SMEs
              </h2>
              <p className="text-muted-foreground text-lg">
                Understanding your waste stream is the first step to better management. Here are the most common materials SMEs generate in Ontario.
              </p>
            </motion.div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {wasteTypes.map((type, index) => (
                <motion.div
                  key={type.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                >
                  <Card variant="default" className="h-full text-center">
                    <CardContent className="p-6">
                      <div className="w-12 h-12 rounded-xl bg-leaf/10 flex items-center justify-center mx-auto mb-4">
                        <type.icon className="h-6 w-6 text-leaf" />
                      </div>
                      <div className="text-3xl font-display font-bold text-leaf mb-2">
                        {type.percentage}
                      </div>
                      <h3 className="font-semibold text-foreground mb-2">{type.title}</h3>
                      <p className="text-sm text-muted-foreground">{type.description}</p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        {/* Why It Matters */}
        <section className="py-16 lg:py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="max-w-3xl mb-16"
            >
              <h2 className="text-3xl lg:text-4xl font-display font-bold text-foreground mb-6">
                Why Proper Waste Handling Matters
              </h2>
              <p className="text-muted-foreground text-lg leading-relaxed">
                Effective waste management isn't just about compliance—it directly impacts your bottom line, your community, and the environment.
              </p>
            </motion.div>

            <div className="grid lg:grid-cols-3 gap-8">
              {impacts.map((impact, index) => (
                <motion.div
                  key={impact.title}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6, delay: index * 0.1 }}
                >
                  <Card variant="nature" className="h-full">
                    <CardContent className="p-8">
                      <div className="w-12 h-12 rounded-xl bg-forest/10 flex items-center justify-center mb-6">
                        <impact.icon className="h-6 w-6 text-forest" />
                      </div>
                      <h3 className="text-xl font-display font-semibold text-foreground mb-3">
                        {impact.title}
                      </h3>
                      <p className="text-muted-foreground leading-relaxed">
                        {impact.description}
                      </p>
                    </CardContent>
                  </Card>
                </motion.div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
};

export default WasteOverview;
